version: 2

project_name: webshare

builds:
  - binary: webshare
    main: .
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/webshare-proxy/webshare-cli/internal/cmd.version=v{{.Version}}
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^Merge "
